### ISSUE TITLE
Question : how does this compare with LMAX Disruptor?

### ISSUE THREAD

**Issue by ghost** [RobAustin/low-latency-primitive-concurrent-queues#1]
So far all the advantages about this queue are also pressent in Disruptor, i wonder if you tried it and what the benchmark resulsts were?

Compared to this queue i guess that Ring buffer has an advantage as it allows consumer to catch up by batch consuming incomming data as it starts to arrive faster...

**Comment by RobAustin** [comment]
Yes - the Disruptor also uses the store-store barrier, but unlike the Disruptor ( which supports multiple consumers ) this ring buffer only supports a single consumer. In other words, this implementation is more focused on a single use case, so I would expect that for a 'single-publisher', 'single consumer', it to perform better than the Disruptor or at worst to perform about the same. But without benchmarking it I don't know, If you get time to run benchmarks agains the Disruptor i'd be interested in the results.
